import Foundation

/// Turns a You/Them-attributed transcript into comprehensive, detail-oriented
/// meeting notes via the user's Quick Add AI provider (OpenAI-compatible).
enum NotesGenerator {

    /// Transcripts beyond this get a clear error rather than a blown context
    /// window. ~80k chars ≈ 7 hours of speech — far past any sane meeting.
    static let maxTranscriptChars = 80_000

    @MainActor
    static func generate(
        transcriptMarkdown: String,
        meetingTitle: String,
        meetingDate: Date?,
        config: QuickAddConfig
    ) async throws -> String {
        guard config.llmEnabled else {
            throw LLMClient.LLMError.network(
                "No AI provider configured — set one under Settings → Quick Add (a key, or local Ollama)."
            )
        }
        guard transcriptMarkdown.count <= maxTranscriptChars else {
            throw LLMClient.LLMError.network(
                "Transcript is unusually long (\(transcriptMarkdown.count) chars) — splitting very long recordings isn't supported yet."
            )
        }

        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .full
        dateFormatter.timeStyle = .short
        let dateLine = meetingDate.map { dateFormatter.string(from: $0) } ?? "Unknown date"

        let system = """
        You are an executive assistant producing meeting notes from a transcript. The transcript attributes \
        speech to "You" (the note-taker) and "Them" (everyone else), with [hh:mm:ss] timestamps.

        Produce comprehensive, detail-oriented notes in Markdown with EXACTLY these sections:

        ## TL;DR
        3 bullets max — what someone who skipped the meeting must know.

        ## Discussion
        Organized by topic (### subheadings), not chronologically. Capture specifics: numbers, names, dates, \
        systems, decisions-in-the-making. Reference key moments with their [hh:mm:ss] timestamp and quote \
        short verbatim phrases for anything contentious or precisely worded.

        ## Decisions
        Bulleted list of decisions actually made (not discussed-and-deferred). If none, say "None recorded."

        ## Action items
        A Markdown table: Owner | Task | Due / timeframe. Use "You" / "Them" / a name if one was spoken. \
        Include items implied by commitments ("I'll send that over"). If none, say "None recorded."

        ## Open questions
        Unresolved questions or deferred topics.

        ## Suggested follow-ups
        2-4 concrete suggestions the note-taker should consider (scheduling, documents to send, people to loop in).

        Be faithful to the transcript — never invent facts. If audio quality clearly garbled a passage, note it.
        """

        let user = """
        Meeting: \(meetingTitle)
        Date: \(dateLine)

        Transcript:

        \(transcriptMarkdown)
        """

        let notes = try await LLMClient.complete(
            system: system,
            user: user,
            baseURL: config.apiBaseURL,
            key: config.openRouterKey,
            model: config.modelID,
            timeout: 180
        )

        let header = """
        # \(meetingTitle)

        *\(dateLine) · notes generated by \(config.modelID)*

        """
        return header + "\n" + notes.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }
}
